### ISSUE TITLE
neutron navigation not working

### ISSUE THREAD

**Issue by Fredyy90** [WaferMouse/L3-37#1]
Hey,

thank you for creating this great multi tool for elite. but it seems like the neutron navigation part ist not working as intended.

when i create a route and import it, everything seems to work fine, but clicking on "copy next system" always puts the name of the very first system on the route in my clipboard.
i seems that it doesn't matter how often i click, i always only get this one system.

am i using it wrong, or is there a bug in the neutron navigation part?

**Comment by WaferMouse** [comment]
"Next" in this case always means the system at the top of the list in the "Details" view. When you visit a system in your route, we clear it from the top of the list (along with any preceding systems)

To demonstrate the intended use, try this:
1. Import a route
2. Expand the "Details" view
3. Click "Copy next system"
4. Hit Ctrl-V in the search in your galaxy map.
5. Visit the system
6. Follow the route by repeating steps 4 and 5. Each time you visit a system in the route after the first system, you'll see systems being removed from the top of the "Details" view, and the clipboard will automatically update to match the first system in the view, ie. the next system to visit in your route.

If you copy something else to your clipboard between steps 4 and 5, you can click "Copy next system" again and carry on to step 5.

**Comment by WaferMouse** [comment]
Ah. That's... weird. I need to have a look at this after work then. As I recall things can be a bit weird near the start of the route. Could you try jumping to the second system and seeing whether that updates things properly? You could also try changing to the dark theme, restarting and trying again, since lots of the theme is set manually and I use the dark theme myself.

**Comment by Fredyy90** [comment]
had to try it in a different system, since i manually moved on with my trip.

I created a new route, imported it and jump in/out of the start system 2-3 times in light theme, nothing happend, didn't trigger the update.

After that i cleared the route, changed the theme to dark and restarted edmc.

Imported the same route again, again jumped in and out of the start system 2 times and i still didn't trigger.

feels like the event from edmc doesn't trigger as expected, parameters are off or your matching of the system name is some how broken.

If it matters, im using Windows 10 in German and Elite + edmc in English

**Comment by WaferMouse** [comment]
Thanks for testing! It's very strange, I was using this only the other day, but it does very much sound as though the event isn't being matched for some reason. I'll have a look when I get a moment this evening.

**Comment by WaferMouse** [comment]
@Fredyy90 I made a very quick release to help me try and debug this: https://github.com/WaferMouse/L3-37/releases/tag/v1.0.3

If you could run EDMC from source, I'm expecting it to output some errors to the console when you try the same tests.  If so, it would be great if you could send me these things:

1. The console output
2. route.json from the edmc-L3-37 folder
3. Your journal file for the session

Thanks in advance! I want to get this working for you, since knowing that people use my work means the world to me :)

**Comment by Fredyy90** [comment]
I'm going to try this tomorrow morning.

Do I have to get the edmc source from github or are all python scripts I
need already In my edmc folder?

Thank you for your effort.


WaferMouse <notifications@github.com> schrieb am Sa., 19. Jan. 2019, 23:11:

**Comment by WaferMouse** [comment]
@Fredyy90 I'm not sure whether you can run it from source using the normal installation files, but so long as you have Python 2 installed you should be able to run it from the release source code zip using python.exe EDMarketConnector.py

https://github.com/Marginal/EDMarketConnector/releases/tag/rel-337

**Comment by Fredyy90** [comment]
I got EDMC running from Source, I think there is a Problem with the upgrade you did to the plugin.

```
Traceback (most recent call last):
  File "C:\Users\frede\Desktop\EDMarketConnector-rel-337\plug.py", line 300, in notify_journal_entry
    newerror = journal_entry(cmdr, system, station, dict(entry), dict(state))
  File "C:\Users\frede\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py", line 1080, in journal_entry
    print(traceback.format_exc())
NameError: global name 'traceback' is not defined
```
I had to add `import traceback` in load.py to get it working.
After the fix and a restart of EDMC I saw this error, i think this explains why the "fleetview" only ever showed 2 of my ships, the ship where it crashed has a non ascii name:

```
Traceback (most recent call last):
  File "C:\Users\frede\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py", line 1079, in journal_entry
    module.journal_entry(cmdr, system, station, entry, state)
  File "C:\Users\frede\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py", line 702, in journal_entry
    self.build_ui()
  File "C:\Users\frede\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py", line 565, in build_ui
    self.ship_widgets.update({ship: ShipFrame(self.ships_scroll.interior, self.ships[ship], urllib.quote_plus(self.cmdr), highlightthickness = 1)})
  File "C:\Users\frede\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py", line 476, in __init__
    self.update_ship(ship_data)
  File "C:\Users\frede\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py", line 487, in update_ship
    self.ship_lbl_txt = "{} ({})".format(ship_data['shipName'],ship_map[ship_data['name'].lower()])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
```

After importing a route and jumping in and out of the start i saw this error everytime your plugin got an event from EDMC. I thought this exception might be blocking everything. 
I than took the time, i flew to this ship to change its name to be 100% ascii, the exceptions stopped and the fleet view showed all my ships for the first time.

I created a short route,` current system -> neighbor  system`, it detected that i was in the start system and copied the next system in my clipboard and when i arrived there, the route disappeared from EDMC, as expected.

The only other exception I could detect in the log was
```
Traceback (most recent call last):
  File "C:\Users\frede\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py", line 1079, in journal_entry
    module.journal_entry(cmdr, system, station, entry, state)
  File "C:\Users\frede\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py", line 949, in journal_entry
    route_offset = len(self.route['result']['system_jumps']) - len(self.queued_systems)
KeyError: 'result'

'result'
```

I cant really check a long neutron route right now without a lot of jumping since im back in the bubble now, but after testing the short route, I think its working fine. 

So the problem is, that your plugin crashes on non-ascii ship names.

**Comment by WaferMouse** [comment]
@Fredyy90 you went above and beyond on diagnosing this, particularly when I screwed up the exception handling, so thanks for that! I'll give you a mention when I post an update on this. I had a sneaky suspicion that it was something in one of the other modules causing this behaviour when I realised I hadn't put a try / except structure in the journal entry loop.

**Comment by WaferMouse** [comment]
@Fredyy90 I've added a fix to support unicode in user content, tested with some umlauts on my ship.  Since it's a grand total of 3 characters and one import statement, I've just updated the 1.0.3 zip to reflect it.  You should be able to rename your ship and see your full fleet now, though there's some weirdness in the way the names will be displayed on restart (JSON encoding issue). https://github.com/WaferMouse/L3-37/releases/tag/v1.0.3
