### ISSUE TITLE
Not working... at least not for EDD-EDMC

### ISSUE THREAD

**Issue by Jugom** [WaferMouse/L3-37#4]
I was curious about all that the plug-in provided, so added it to my plugins folder. but I don't see anything in the settings tab. I re-pasted the folder and restarted the program multiple times, but nothing. the only other plugin I have installed is the distance calculator, and that one is working normally.

**Comment by Crispy** [comment]
Renaming the folder to "edmc-L3-37" fixed this issue for me.

**Comment by Jugom** [comment]
> Renaming the folder to "edmc-L3-37" fixed this issue for me.

sadly that's the exact name of mine. So I'm guessing that's the default name.
C:\Users\username\AppData\Local\EDD-EDMC\plugins\edmc-L3-37

**Comment by Crispy** [comment]
You can try looking in %TEMP%/EDMarketConnector/EDMarketConnector-debug.log and see if you can determine what the error you're having is.

**Comment by WaferMouse** [comment]
@Crispy Just to confirm, are you using the plugin with EDD-EDMC? Because I didn't even know that was a thing, so if my plugin works with it that's kinda amazing.

**Comment by Crispy** [comment]
Oh wow, I'm really sorry. I didn't read the title carefully at all. I'm just using EDMC.

**Comment by Jugom** [comment]
> You can try looking in %TEMP%/EDMarketConnector/EDMarketConnector-debug.log and see if you can determine what the error you're having is.

Plugin edmc-L3-37
Adding edmc-L3-37
loading plugin edmc-L3-37 from "C:\Users\username\AppData\Local\EDD-EDMC\plugins\edmc-L3-37\load.py"
Traceback (most recent call last):
  File "plug.pyc", line 95, in __init__
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\username\AppData\Local\EDD-EDMC\plugins\edmc-L3-37\load.py", line 15, in <module>
    from chat_viewer import ChatViewer
  File "C:\Users\username\AppData\Local\EDD-EDMC\plugins\edmc-L3-37\chat_viewer.py", line 10, in <module>
    from web_handlers import *
  File "C:\Users\username\AppData\Local\EDD-EDMC\plugins\edmc-L3-37\web_handlers.py", line 9, in <module>
    with open(path.join(config.respath, 'systems.p'),  'rb') as h:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\EDD-EDMC\\systems.p'

-----
in case it tells you something. this is as good as chinese for me xD

**Comment by Jugom** [comment]
> @Crispy Just to confirm, are you using the plugin with EDD-EDMC? Because I didn't even know that was a thing, so if my plugin works with it that's kinda amazing.

I've installed a few more plugins (DistanceCalc, EDMC-HourlyIncome, HabZone, Spansh Router) and all of them are working fine. so looks like yours is the only one not so friendly 😬

**Comment by WaferMouse** [comment]
I'm not surprised, L3-37 is more complex than other plugins, in some ways, but this looks like a fairly easy fix, or at least a workaround. Thanks for posting the log!

**Comment by WaferMouse** [comment]
@Jugom I've got a chance to look into this now. Where did you find that log file that you posted?

**Comment by Jugom** [comment]
I just went to %temp% and it's there, not in a folder but a .log file "EDD-EDMC.log"

**Comment by WaferMouse** [comment]
@Jugom Thanks, I knew it'd be something obvious :) Great news, I already have a fix working, I just need to check that it all works in regular EDMC before I release.

**Comment by Jugom** [comment]
That's great! Looking forward to test it out!

**Comment by jasehuss** [comment]
I am having the very same issue with EDD-EDMC so I'm looking forward to this fix.
Thanks for your efforts WaferMouse

**Comment by Jugom** [comment]
They just Updated the EDD-EDMC tool and this plugin is now working.

**Comment by WaferMouse** [comment]
It doesn't make much difference, since the thing that was breaking it before will break it again very soon, per #5 . Fortunately, I just started a week off work, so I'm going to finish the fix that I already started right now, and I'm going to do it properly not that I know the EDDB endpoints. Everyone will need to download the next update, regardless of whether they're on EDMC or EDD.

**Comment by WaferMouse** [comment]
Closed as of latest release. You'll want to update @Jugom @jasehuss as this release includes a workaround for changing the system and station providers that you're otherwise missing in EDD-EDMC.
