### ISSUE TITLE
Highlighting of systems where refueling is required

### ISSUE THREAD

**Issue by ra3ggi** [WaferMouse/L3-37#9]
Hi! Thank you very much for the good tool. There is one wish. In Neutron Navigator, please make a highlighting of systems where refueling is required. It will be VERY useful!

**Comment by WaferMouse** [comment]
This feature is already in the plugin. The neutron navigator uses solid lines and dotted lines in the same way that the in-game galaxy map does.

**Comment by ra3ggi** [comment]
Perhaps this feature is not working properly. Two days ago I flew to Colonia on the navigator https://www.spansh.co.uk/exact-plotter - there is no match dotted lines and refueling. The reason is that there are systems that need refueling from both a neutron star and an ordinary star in the same system.

**Comment by WaferMouse** [comment]
Oh okay, you're talking specifically about the fuel stops in the exact plotter. I can look into that in a few days, probably.

**Comment by ra3ggi** [comment]
I'll be waiting. I still have to fly back :)

**Comment by WaferMouse** [comment]
Added in the latest release: https://github.com/WaferMouse/L3-37/releases/tag/110
